# CONFIGURACION DE POSTGRESQL
spring.datasource.url=jdbc:postgresql://db:5432/practicapokemon_db
spring.datasource.username=ubu_user
spring.datasource.password=ubu_password

# Configuracion de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CONFIGURACION DE INTEGRACION
api.python.url=http://python-api:5000/api/pokemon/

# Consola H2 (opcional por si cambias a H2)
spring.h2.console.enabled=true
spring.headers.frame-options=sameorigin